// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPrFeBX5YvXj2GZS5Pig6SI2tJn57G5-Y',
    appId: '1:729687866384:ios:e1505cdc159e877b4b1e95',
    messagingSenderId: '729687866384',
    projectId: 'ahaarproject',
    storageBucket: 'ahaarproject.firebasestorage.app',
    iosBundleId: 'com.example.ahaarProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLc6EvVlzcqa_kysW2i7CsJi-Ttegp-8Y',
    appId: '1:729687866384:web:8c16e36dfcfe10a94b1e95',
    messagingSenderId: '729687866384',
    projectId: 'ahaarproject',
    authDomain: 'ahaarproject.firebaseapp.com',
    storageBucket: 'ahaarproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPrFeBX5YvXj2GZS5Pig6SI2tJn57G5-Y',
    appId: '1:729687866384:ios:e1505cdc159e877b4b1e95',
    messagingSenderId: '729687866384',
    projectId: 'ahaarproject',
    storageBucket: 'ahaarproject.firebasestorage.app',
    iosBundleId: 'com.example.ahaarProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJgZFlT9ee2bkJvmWV1H3Esc7OjnlZzo',
    appId: '1:729687866384:android:f6017b917e3fb7574b1e95',
    messagingSenderId: '729687866384',
    projectId: 'ahaarproject',
    storageBucket: 'ahaarproject.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLc6EvVlzcqa_kysW2i7CsJi-Ttegp-8Y',
    appId: '1:729687866384:web:2fd51d1faa4bed2c4b1e95',
    messagingSenderId: '729687866384',
    projectId: 'ahaarproject',
    authDomain: 'ahaarproject.firebaseapp.com',
    storageBucket: 'ahaarproject.firebasestorage.app',
  );

}